imagenet_templates = [
    'a bad photo of a {}.',
    'a photo of many {}.',
    'a sculpture of a {}.',
    'a photo of the hard to see {}.',
    'a low resolution photo of the {}.',
    'a rendering of a {}.',
    'graffiti of a {}.',
    'a bad photo of the {}.',
    'a cropped photo of the {}.',
    'a tattoo of a {}.',
    'the embroidered {}.',
    'a photo of a hard to see {}.',
    'a bright photo of a {}.',
    'a photo of a clean {}.',
    'a photo of a dirty {}.',
    'a dark photo of the {}.',
    'a drawing of a {}.',
    'a photo of my {}.',
    'the plastic {}.',
    'a photo of the cool {}.',
    'a close-up photo of a {}.',
    'a black and white photo of the {}.',
    'a painting of the {}.',
    'a painting of a {}.',
    'a pixelated photo of the {}.',
    'a sculpture of the {}.',
    'a bright photo of the {}.',
    'a cropped photo of a {}.',
    'a plastic {}.',
    'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.',
    'a blurry photo of the {}.',
    'a photo of the {}.',
    'a good photo of the {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'a photo of one {}.',
    'a doodle of a {}.',
    'a close-up photo of the {}.',
    'a photo of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'a low resolution photo of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a photo of the clean {}.',
    'a photo of a large {}.',
    'a rendition of a {}.',
    'a photo of a nice {}.',
    'a photo of a weird {}.',
    'a blurry photo of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a sketch of the {}.',
    'a embroidered {}.',
    'a pixelated photo of a {}.',
    'itap of the {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a plushie {}.',
    'a photo of the nice {}.',
    'a photo of the small {}.',
    'a photo of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a drawing of the {}.',
    'a photo of the large {}.',
    'a black and white photo of a {}.',
    'the plushie {}.',
    'a dark photo of a {}.',
    'itap of a {}.',
    'graffiti of the {}.',
    'a toy {}.',
    'itap of my {}.',
    'a photo of a cool {}.',
    'a photo of a small {}.',
    'a tattoo of the {}.',
]

cifar100_templates = [
    'a photo of a {}.',
    'a blurry photo of a {}.',
    'a black and white photo of a {}.',
    'a low contrast photo of a {}.',
    'a high contrast photo of a {}.',
    'a bad photo of a {}.',
    'a good photo of a {}.',
    'a photo of a small {}.',
    'a photo of a big {}.',
    'a photo of the {}.',
    'a blurry photo of the {}.',
    'a black and white photo of the {}.',
    'a low contrast photo of the {}.',
    'a high contrast photo of the {}.',
    'a bad photo of the {}.',
    'a good photo of the {}.',
    'a photo of the small {}.',
    'a photo of the big {}.',
]

ethec_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low-resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a beautiful painting of a {}.",
    "an artistic sketch of a {}.",
    "a close-up photo of the intricate details on a {}.",
    "a photo of a rare species of {}.",
    "a digital artwork featuring a {}.",
    "an illustration of a colorful {}.",
    "a photo of a {} in its natural habitat.",
    "a blurry image of a flying {}.",
    "a photo of a tiny {} on a flower petal.",
    "a creative collage with various {} species.",
    "a vintage photograph of a {}.",
    "a silhouette of a {} against the sunset.",
    "a minimalist drawing of a {}.",
    "a photo of a {} with vibrant colors.",
    "a digital painting of a {} in motion.",
    "an abstract representation of a {}.",
    "a photo of a {} with its wings spread wide.",
    "a black and white image of a {}.",
    "a photo of a {} perched on a branch.",
    "a watercolor painting of a {}.",
    "a photo of a {} taken from a unique angle.",
    "an animated depiction of a {}.",
    "a photo of a {} with iridescent wings.",
    "a sketch of a {} in mid-flight.",
    "a photo of a {} camouflaged in its environment.",
    "a collage of different stages of a {}'s life cycle.",
    "an impressionist-style painting of a {}.",
    "a photo of a {} with intricate patterns.",
    "a neon artwork inspired by a {}.",
    "a photo of a {} with translucent wings.",
    "a realistic drawing of a {}.",
    "a photo of a {} resting on a leaf.",
    "an origami representation of a {}."
]